### ISSUE TITLE
Nowruz judging is not working.

### ISSUE THREAD

**Issue by LeonardoValente** [kunyavskiy/ioi-on-codeforces#1]
Currently nowruz from 2017 doesnt seem to be working correctly. I (definitelynotmee on cf) submitted my outputs that got around 70 points on oj.uz and it got 100 points here.

Also since you guys added the sample in the input file, the range of the important test cases goes from 2 to 11 instead of 1 to 10 like the original, and its kind of aesthetically unpleasing and annoying to format (ofc, just a nitpick, the 100 points thing is much more important lol).

**Comment by kunyavskiy** [comment]
Thank you!

I've fixed scoring, just a bug around converting points to percentages of points. Compared points with 10 after converting it to percentages. 

As for the sample, I don't know. I think the ability to submit a sample is good for checking you are doing it correctly in a technical way, like naming files, output formatting, etc. While extra file adds neither scripting nor handwork significantly harder.
