### ISSUE TITLE
Standings issue

### ISSUE THREAD

**Issue by Ghulam-Junaid** [kunyavskiy/ioi-on-codeforces#10]
Hi! I did IOI 2007 virtual a few days ago. I got 25 points on problem C, but then I resubmitted a little later and got 5 points. The standings of the contest show 25 points ( https://codeforces.com/group/32KGsXgiKA/contest/103750/standings ), But in the other standings ( https://codeforces.com/group/32KGsXgiKA/customrating/3853 ) it shows 5 points. I don't really know if the points of last submission matter or the points maximum overall. Kindly fix it (strikethrough : such that I get 25 on both). Thanks.

**Comment by kunyavskiy** [comment]
Sorry, that's a codeforces issue, not an archive one. I have forwarded it to Mike.
