### ISSUE TITLE
Error in sample input

### ISSUE THREAD

**Issue by Edu175** [kunyavskiy/ioi-on-codeforces#11]
In [IOI 2016 Day 1](https://codeforces.com/group/32KGsXgiKA/contest/103772) problem [B. Roller Coaster Railroad](https://codeforces.com/group/32KGsXgiKA/contest/103772/problem/B) there is an extra $1$ in the first line of the sample input.

**Comment by kunyavskiy** [comment]
Fix. This was caused by internal and external graders having a bit different input format.
