### ISSUE TITLE
(Minor) IOI2021F Registers

### ISSUE THREAD

**Issue by BThero** [kunyavskiy/ioi-on-codeforces#3]
[Here](https://codeforces.com/group/32KGsXgiKA/contest/103784/problem/F) is the problem link.

The attached grader file is not the same as the grader described in the statement and the actual correct grader in on the [official 2021 website](https://ioi2021.sg/ioi-2021-tasks/)

Also, the attached archive does not contain sample input files for the grader.

**Comment by kunyavskiy** [comment]
Fixed
