### ISSUE TITLE
IOI 2002 XOR is listed as regular problem instead of output-only problem on Codeforces

### ISSUE THREAD

**Issue by qpwoeirut** [kunyavskiy/ioi-on-codeforces#7]
[Problem link](https://ioi.contest.codeforces.com/group/32KGsXgiKA/contest/103699/problem/C)

The statement for XOR says that it's an output-only problem, but on Codeforces you are required to submit code instead of a zip archive.

**Comment by kunyavskiy** [comment]
Thank you for report fixed this.
