### ISSUE TITLE
An issue in IOI 2010 Day 2 Problem 4 (2010 - H, Saveit) 

### ISSUE THREAD

**Issue by Ghulam-Junaid** [kunyavskiy/ioi-on-codeforces#9]
The issue is in the grader file. The task says that you can do encode_bit(b) where b is either 0 or 1, but the grader allows for any value. So, we can basically store integers, this way we can just for every pair of vertices (u, v) encode_bit(dist(u, v)) and then get this distance in decode and just call hops on it. (This will only take H * N calls to encode_bit). Kindly fix the issue and rejudge the submissions.

Thanks.

Ghulam Junaid.

**Comment by kunyavskiy** [comment]
Thanks for your finding. I've fixed it, and will rejudge existing submissions soon. Do you have a submission where I can check that fix helped?

**Comment by Ghulam-Junaid** [comment]
Thanks, it worked. Actually, I hadn't submit myself, my friend submitted and got it accepted. Here is the link of his submission : https://ioi.contest.codeforces.com/group/32KGsXgiKA/contest/103757/submission/237678468	

I also wanted to say, Thanks for the ioi archive and keeping it updated.

**Comment by kunyavskiy** [comment]
Thanks, checked, that it's now getting 0.
